# Numpy

# Lists

In [12]:
import array

In [2]:
# Python List
l=list(range(10))

In [3]:
print(l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [4]:
type(l[0])

int

In [5]:
type(l)

list

In [6]:
la=[str(i) for i in l]

In [7]:
print(la)

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']


In [8]:
type(la)

list

In [9]:
type(la[0])

str

In [11]:
[type(i) for i in la]

[str, str, str, str, str, str, str, str, str, str]

In [2]:
import numpy as np

In [14]:
#Creating array from python lists

In [20]:
a=np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [18]:
np.array([1,2,3,4,5], dtype='float32')

array([1., 2., 3., 4., 5.], dtype=float32)

In [24]:
np.array([range(i,i+3) for i in [1,2,3]])

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [25]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [26]:
np.ones((3,5),dtype=int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [27]:
np.full((3,5),53)

array([[53, 53, 53, 53, 53],
       [53, 53, 53, 53, 53],
       [53, 53, 53, 53, 53]])

In [28]:
np.full((23,23),0)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0

In [30]:
import random
import string

In [33]:
B=string.ascii_lowercase
print(B)

abcdefghijklmnopqrstuvwxyz


In [35]:
np.full((10,2),random.choice(B))

array([['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g'],
       ['g', 'g']], dtype='<U1')

In [37]:
np.arange(1,21,2)

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
np.linspace(2,20,20)

array([ 2.        ,  2.94736842,  3.89473684,  4.84210526,  5.78947368,
        6.73684211,  7.68421053,  8.63157895,  9.57894737, 10.52631579,
       11.47368421, 12.42105263, 13.36842105, 14.31578947, 15.26315789,
       16.21052632, 17.15789474, 18.10526316, 19.05263158, 20.        ])

In [44]:
np.random.random((3,3))

array([[0.49421036, 0.28387742, 0.79025283],
       [0.55772055, 0.21287979, 0.71622977],
       [0.4820376 , 0.71317879, 0.89152552]])

In [45]:
np.random.randint(0,10,(3,3))

array([[3, 5, 0],
       [9, 4, 0],
       [0, 9, 9]])

In [49]:
np.random.randint(10,size=(3,3))

array([[6, 0, 9],
       [2, 1, 4],
       [4, 7, 7]])

In [52]:
np.random.randint(0,10,(3,3,3))

array([[[3, 8, 3],
        [2, 8, 7],
        [8, 8, 3]],

       [[7, 3, 0],
        [6, 2, 9],
        [2, 4, 7]],

       [[9, 4, 3],
        [9, 7, 2],
        [1, 1, 2]]])

In [47]:
#Identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
#Array Slicing x[start:stop:step]   x[start:stop:step,start:stop:step]
x=np.arange(10)
x[:5]

array([0, 1, 2, 3, 4])

In [57]:
x[2:8:2]

array([2, 4, 6])

In [6]:
#Arrya COncat and split
x=[1,2]
y=[3,4]
z=np.concatenate([x,y])

In [12]:
print(z)
#a,b,c= np.split[z,[1,2]]

[1 2 3 4]


In [14]:
x=np.arange(5)
print(x)
print(x*2)
print(x**2)

[0 1 2 3 4]
[0 2 4 6 8]
[ 0  1  4  9 16]


In [16]:
np.add(x,2)
#subtract, negative, multiply, divide, floor_divide,power, mod

array([2, 3, 4, 5, 6])

In [17]:
abs(x) #absolute value or np.absolute(x)

array([0, 1, 2, 3, 4])

In [18]:
np.absolute(x)

array([0, 1, 2, 3, 4])

In [20]:
#sin(x), cos(x)

In [26]:
x=[1,2,3]
print(x)
print(np.exp(x))
print(np.exp2(x)) #2^x
print(np.log(x)) #ln
print(np.log2(x)) #log2

[1, 2, 3]
[ 2.71828183  7.3890561  20.08553692]
[2. 4. 8.]
[0.         0.69314718 1.09861229]
[0.        1.        1.5849625]


In [32]:
x=np.arange(1,5)
print(x)
sum=np.add.reduce(x)
print(sum)
np.add.accumulate(x)

[1 2 3 4]
10


array([ 1,  3,  6, 10], dtype=int32)

In [29]:
np.multiply.reduce(x)

24

In [33]:
np.multiply.accumulate(x)

array([ 1,  2,  6, 24], dtype=int32)

In [35]:
#min max and others

In [37]:
x=np.arange(10)
np.sum(x)

45

In [38]:
np.max(x)  #sum min prod mean std var argmin median percentile any all

9